services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    networks:
      - wisher-network
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wisher
      - POSTGRES_USER=wuser
      - POSTGRES_PASSWORD=wpassword
      - POSTGRES_PORT=5432
    container_name: postgres
    restart: always

  kafka:
    image: bitnami/kafka:3.9.0-debian-12-r3
    networks:
      - wisher-network
    volumes:
      - ./kafka:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://192.168.10.200:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"
      - "9094:9094"
    container_name: kafka
    restart: always


  milvus:
    image: milvusdb/milvus:v2.4.15
    networks:
      - wisher-network
    volumes:
      - ./milvus/db:/var/lib/milvus
      - ./milvus/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./milvus/user.yaml:/milvus/configs/user.yaml
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    ports:
      - "2379:2379"
      - "19530:19530"
      - "9091:9091"
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    container_name: milvus
    restart: always
    command: ["milvus", "run", "standalone"]

  wisher_app:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    image: wisher_ml:1.0.0
    environment:
      - DB_DATABASE=wisher
      - DB_USER=wuser
      - DB_PASSWORD=wpassword
      - DB_HOST=postgres
      - DB_PORT=5432
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    networks:
      - wisher-network
    volumes:
      - ./src:/project
    depends_on:
      - postgres
      - kafka
      - milvus
    container_name: wisher_app
    restart: always

networks:
  wisher-network:
    driver: bridge
